### ISSUE TITLE
Deprecate multiselect UI feature

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#541]
**Is your feature request related to a problem? Please describe.**
The multiselect google sheet manifest feature provides a dialog for users to enter comma-separated items by checkbox-ing them from a list of valid values based on the data model schema.  

Currently the multiselect UI in google sheet manifests works only in Firefox. It used to work in other browsers, but this AppScript code is no longer being rendered properly. 

This makes the feature unevenly available and applicable to a niche set of users. 

Furthermore, @mialy-defelice has developed validation rules that integrate with google sheet (e.g. regex match) that would provide realtime feedback to users wrt whether they are entering a well-formatted list of items. This couples with the 'list' validation rule that checks the items entered by the user comply with the data model schema.  

Supporting the UI-related AppScript authentication credential mechanism and documentation requires extra effort. E.g. every other Google service schematic uses is w/in the scope of service account credentials. The Google AppScript REST API is not w/in the scope of Google service-accounts. Google service-accounts are much easier to setup by users installing schematic compared to the credentials required to enable AppScript.

**Describe the solution you'd like**
I suggest we deprecate the multiselect UI feature in lieu of the above validation rules approach.

This requires:
- [ ] removing instructions to use the multiselect UI during manifest generation
- [ ] removing credentials enabling AppScript from the schematic config file
- [ ] writing a regex checking for a properly formatted comma-separated string of items
- [ ] adding the above regex to items in schema that currently have the 'list' validation rule
- [ ] updating installation documentation to reflect these changes

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**
We have users that try installing schematic; bump into credentials setup problems and are blocked or have to use DC app GUI which is inconvenient for batch operations like generating all manifests for 20 datasets.

@mialy-defelice and I have discussed this solution during code review and it seems a good path forward.

**Comment by milen-sage** [comment]
@ychae could we triage and, if you think this is something we are moving forward with, can you create the corresponding github issues to keep track of the items related to this Epic?

**Comment by ychae** [comment]
@milen-sage Do we know if there are a subset of users that are using the multi-select issue? I don't think we do, but we should get the messaging right so that we don't cause any stumbles if that's what the end users are expecting. 

I agree that if it makes installing schematic easier, we should totally bump this up in priority and get the patches in.

**Comment by milen-sage** [comment]
Yes, in HTAN, we have had a couple of centers. However, one of them is HTAPP (no longer submitting data) and the other ones have started filling in templates automatically once they figured out the template. 

You are bringing up a good point though. We should communicate w/ users. I think having a 'soft' statement that the feature is being deprecated, part of a broader statement on UI and other improvements, would work well.
