### ISSUE TITLE
Validation Rules Refactor

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#577]
**Is your feature request related to a problem? Please describe.**
1. [Manifest validation rules](https://sagebionetworks.jira.com/wiki/spaces/SCHEM/pages/2473623559/The+Data+Model+Schema#A.-Schema-properties-and-relationships) are written in-house for our use cases and so must be maintained in-house, but analogous rules likely exist and are maintained elsewhere.
2. Validation errors are hard coded in [`validate_attribute.py`](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/models/validate_attribute.py), so each error must be explicitly defined.
3. Manifest validation is currently limited to a maximum of two validation rules that must be of list and regex form. 

**Describe the solution you'd like**
- [x] Replace validation rules in our codebase with those present in [public libraries](https://greatexpectations.io/) as appropriate to simplify the codebase and lessen the required in-house maintenance.
- [ ] Dynamically generate validation error messages as appropriate to reduce complexity.
- [ ] Expand the number of allowed rules (beyond 2)
- [x] Expand the rules available to use (beyond list and regex, ex. allowing list and URL matching) to allow for more flexibility in manifest structure and validation.

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Long-term - 6 months - 1 year

**Additional context**
Other necessary refactors discovered will be defined in the future.

**Comment by GiaJordan** [comment]
I think this covers everything from our previous discussions but please let me know of or add anything I missed.
@milen-sage @mialy-defelice

**Comment by milen-sage** [comment]
Yes, this looks great @GiaJordan !

**Comment by milen-sage** [comment]
Acceptance criteria - in addition, to the check items above, add documentation for usage of refactored rules and new features.

**Comment by GiaJordan** [comment]
Modified acceptance criteria:
1 Manifest validation will use a combination great expectations and in house validation functions for the time being until other necessary expectations are moved into production

**Comment by GiaJordan** [comment]
`schematic model validate` now uses a hybrid approach for manifest validation. A combination of in-house validation rules and Great Expectations are used for validation with splits as follows below. The GE results are parsed and passed to existing functions to generate error messages for now.

In-house Validation Rules:
- List::Regex
- Regex search
- list
- url

Great Expectations:
- num
- int/float/string
- regex match

@ychae

**Comment by GiaJordan** [comment]
#198 Created by @milen-sage  as subtask for task 3: rule expansion
Will try approach utilizing Great Expectations

**Comment by GiaJordan** [comment]
**Rule Expansion:** 
- [ ] Cross Manifest Validation
- [ ] DCC Validation Rules

(will be updated as appropriate)

**Comment by GiaJordan** [comment]
@rrchai reported an issue with the errors raised during cross-manifest validation that I'll need to look into, but I don't think its big enough to warrant a separate ticket
**cc** @ychae @milen-sage

**Comment by GiaJordan** [comment]
The GE flag and bug fix for error messages have been implemented on the [refactor branch](https://github.com/Sage-Bionetworks/schematic/pull/614) and are working well, per @rrchai 
@ychae @milen-sage

**Comment by GiaJordan** [comment]
@ychae converted to milestone where tracking will continue, closing issue
