### ISSUE TITLE
Incorporate collapse and expand into schema visualization 

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#715]
**Is your feature request related to a problem? Please describe.**
Incorporate new interactions to nodes in schema visualization

- [x] zoom in /zoom out
- [x] expand
- [x] collapse

**Describe the solution you'd like**
Incorporate some of Adam's design and begin to experiment adding more interactions to schema visualization 

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**

**Comment by linglp** [comment]
More tasks: 

- [ ] add links. Ensure that paths could exit and enter like nodes and text
- [ ] Modify text and nodes based on Mialy's suggestion. If a child belongs to other nodes, and other parents have not yet been exited, the text/node of the child should still be there. 
- [ ] Modify links based on Mialy's suggestion. When click on a node, all the links belong to that node should be entered/exited. 
- [ ] add D3 transition animation

**Comment by ychae** [comment]
@linglp I've created a [milestone](https://github.com/Sage-Bionetworks/schematic/milestone/27) to help track this epic. If the tasks above are converted into new issues, I'll be sure to add them to this milestone for easier tracking.

**Comment by milen-sage** [comment]
Let's keep going with this issue in sprint 11! The checkboxes above reflect the remaining work based on conversation with @linglp, with one addition:

- [ ] add support for skip-level connections and use the NF model as an example

This would facilitate the clean-up task in step 3 above (e.g. removing hardcoding, testing with a new model, etc.).

**Comment by linglp** [comment]
@milen-sage @ychae I have refactored the part related to links and also have most of the collapse and expand interaction work for NF in the past sprint. There are still some problems when I try to expand the higher level after collapsing and expanding the lower level nodes.

**Comment by milen-sage** [comment]
For step 6, @linglp could you coordinate with @mialy-defelice this sprint on what functions the backend REST API needs to provide, if any, in addition to the existing endpoints in order to recapitulate the current schema visualization state and the information in the attribute table? 

If there's work needed on the backend let's capture and prioritize it for this sprint.

**Comment by linglp** [comment]
@milen-sage Here's the issue for Mialy: https://github.com/Sage-Bionetworks/schematic/issues/833

**Comment by linglp** [comment]
Close this issue for now since most of the code cleaning has already finished. I will open new issues to document new tasks.
