### ISSUE TITLE
Review the dev environment of Sage-Bionetworks/schematic

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/schematic#786]
One of my objectives is to improve the development environments of software developers at Sage by sharing my expertise in software architecture and development. A good first candidate is a repo with contributions from 2+ active developers and who use a programming language such as Python, Java or TypeScript (the programming languages I'm most experienced with). Milen took up the offer and asked me to review [Sage-Bionetworks/schematic](https://github.com/Sage-Bionetworks/schematic).

## Possible improvements (June 2022)

- [ ] Uniformize developer experience using Visual Studio Code Dev Containers
- [ ] Automatically fix linter issues when saving Python files
- [ ] Enable developers to work on remote hosts (EC2) using VS Code and devcontainers
- [ ] Simplify installation & installation doc when using a devcontainer
- [ ] Simplify GitHub workflows using a devcontainer
- [ ] Speed up GitHub workflows using caching
- [ ] Move contribution guidelines to CONTRIBUTING.md
- [ ] Redirect to Sage Bionetworks' Code of Conduct
- [ ] Validate OpenAPI document
- [ ] Containerize the REST API service
- [ ] Prevent sensitive configuration values from being committed to GH
- [ ] Describe the components of this project
  - The README should describe whether this project is an app, library, API service, etc.
- [ ] Clarify how this project can be deployed and used
  - The README should describe how to start the app or a snippet of code that shows how to use this project (if it's a library).

**Comment by tschaffter** [comment]
Additional context:

Thomas:

> Hi Milen, I had a quick look at Schematic repo. I identified a few improvements that could be applied to uniformize the developer experience and make development more efficient. If you want to learn more about each improvement, I'm happy to jump in a call. I can also convert this [ticket "draft"](https://github.com/orgs/Sage-Bionetworks/projects/44/views/1) into an actual ticket in the Schematic repo to open the conversation to other developers.

Milen:

> Yes, please feel free to start the issue; if you can have the list formatted with checkboxes that would be great. I think some of the items may be applicable and some may not be at this time.
> This is probably an epic actually, and we’ll have to break down the different applicable options in their own issues that can be triaged across sprints.
