### ISSUE TITLE
modify attribute table for schema viz 

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#884]
**Is your feature request related to a problem? Please describe.**
Based on Adam's [new design](https://www.loom.com/share/8365bb25bdf54887bc5c39a194fcc4b0) and our discussion today, here's a list of changes: 

First priority: 
- [x] move location of filter to attribute table
- [x] when no node is selected, don't show anything in the attribute table
- [x] when text in the description column gets too long, truncate the text and use a plus sign to indicate that the column could be expanded. When clicking on the plus sign, the height of rows increases
- [x] Reword conditional requirements based on Adam's proposal (this will need to wait until schema viz fully connects with API endpoints)
- [x] Content lines and tooltips to indicate root nodes

Second priority: 
- [x] The "slide in effect" in Adam's design. When clicking on the the "View table" button, the attribute table shows up 

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by linglp** [comment]
Note: for sprint 19, I will on the following related to the attribute table:

- [ ] Turn the content lines fader and lighter
- [ ] modify text in "conditional requirement" column in attribute table

**Comment by milen-sage** [comment]
@linglp could you move the items in third priority in the first comment to their own issue? Will address those later.
